export const mockUsers = [
	{
		id: "mockUserId1",
		handle: "mockUserId1",
		profile: "mockUserId1",
		twitterHandle: "mockUserId1",
		createdAt: new Date(),
		updatedAt: new Date(),
		totalPoints: 0,
		isAi: false,
		name: "mockUserId1",
		image: "/test-user.png",
		plan: "free",
		hasGeminiApiKey: false,
	},
	{
		id: "mockUserId2",
		handle: "mockUserId2",
		profile: "mockUserId2",
		twitterHandle: "mockUserId2",
		createdAt: new Date(),
		updatedAt: new Date(),
		totalPoints: 0,
		isAi: false,
		name: "mockUserId2",
		image: "mockUserId2",
		plan: "free",
		hasGeminiApiKey: false,
	},
];
