/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --env-interface=CloudflareBindings` (hash: 78677c0589c30018dc61d78c80111c0b)
interface __BaseEnv_CloudflareBindings {
	TIPITAKA_READ_MODELS: KVNamespace;
	TRANSLATION_QUEUE: Queue;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
