/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type {
	ImportFileStatus,
	ImportRunStatus,
	JsonValue,
	TipitakaTextLevel,
	TranslationProofStatus,
	TranslationStatus,
} from "../drizzle/types";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface Accounts {
	accessToken: string | null;
	accessTokenExpiresAt: Date | null;
	accountId: string;
	createdAt: Generated<Date>;
	id: string;
	idToken: string | null;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	refreshTokenExpiresAt: Date | null;
	scope: string | null;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface GeminiApiKeys {
	apiKey: Generated<string>;
	id: Generated<number>;
	userId: string;
}

export interface ImportFiles {
	checksum: string | null;
	finishedAt: Date | null;
	id: Generated<number>;
	importRunId: number;
	message: Generated<string>;
	path: string;
	startedAt: Generated<Date>;
	status: Generated<ImportFileStatus>;
}

export interface ImportRuns {
	finishedAt: Date | null;
	id: Generated<number>;
	message: Generated<string>;
	startedAt: Generated<Date>;
	status: Generated<ImportRunStatus>;
}

export interface Notifications {
	actorId: string;
	createdAt: Generated<Date>;
	id: Generated<number>;
	read: Generated<boolean>;
	segmentTranslationId: number;
	userId: string;
}

export interface PageLocaleTranslationProofs {
	id: Generated<number>;
	locale: string;
	pageId: number;
	translationProofStatus: Generated<TranslationProofStatus>;
}

export interface SegmentAnnotationLinks {
	annotationSegmentId: number;
	targetSegmentId: number;
}

export interface SegmentMetadata {
	createdAt: Generated<Date>;
	id: Generated<number>;
	metadataTypeId: number;
	segmentId: number;
	value: string;
}

export interface SegmentMetadataTypes {
	id: Generated<number>;
	key: string;
	label: string;
}

export interface Segments {
	createdAt: Generated<Date>;
	id: Generated<number>;
	number: number;
	sourceBookCode: string | null;
	sourceChapterNumber: number | null;
	sourceParagraphNumber: string | null;
	sourceParagraphOccurrence: number | null;
	text: string;
	textAndOccurrenceHash: string;
	tipitakaPageId: number;
}

export interface SegmentTranslations {
	createdAt: Generated<Date>;
	id: Generated<number>;
	locale: string;
	point: Generated<number>;
	segmentId: number;
	text: string;
	userId: string;
}

export interface SegmentWords {
	endOffset: number;
	id: Generated<number>;
	position: number;
	segmentId: number;
	startOffset: number;
	surface: string;
}

export interface SelectedSegmentTranslations {
	locale: string;
	segmentId: number;
	selectedAt: Generated<Date>;
	selectedByUserId: string | null;
	translationId: number;
}

export interface SelectedWordGlosses {
	glossId: number;
	locale: string;
	selectedAt: Generated<Date>;
	selectedByUserId: string | null;
	wordId: number;
}

export interface Sessions {
	createdAt: Generated<Date>;
	expiresAt: Date;
	id: string;
	ipAddress: string | null;
	token: string;
	updatedAt: Generated<Date>;
	userAgent: string | null;
	userId: string;
}

export interface TipitakaPageAnnotationTargets {
	annotationPageId: number;
	position: Generated<number>;
	targetPageId: number;
}

export interface TipitakaPages {
	catalogKey: string;
	createdAt: Generated<Date>;
	id: Generated<number>;
	importFileId: number | null;
	mdastJson: JsonValue;
	parentId: number | null;
	position: Generated<number>;
	slug: string;
	textLevel: TipitakaTextLevel | null;
	updatedAt: Generated<Date>;
}

export interface TipitakaReadModelJobs {
	attempts: Generated<number>;
	lastError: Generated<string>;
	locale: string;
	pageId: number;
	requestedAt: Generated<Date>;
}

export interface TranslationJobs {
	aiModel: string;
	createdAt: Generated<Date>;
	error: Generated<string>;
	id: Generated<number>;
	locale: string;
	pageId: number;
	progress: Generated<number>;
	status: Generated<TranslationStatus>;
	updatedAt: Generated<Date>;
	userId: string | null;
}

export interface TranslationVotes {
	createdAt: Generated<Date>;
	isUpvote: boolean;
	translationId: number;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface Users {
	createdAt: Generated<Date>;
	email: string;
	emailVerified: boolean | null;
	handle: string;
	id: string;
	image: Generated<string>;
	isAi: Generated<boolean>;
	name: Generated<string>;
	plan: Generated<string>;
	profile: Generated<string>;
	provider: Generated<string>;
	totalPoints: Generated<number>;
	twitterHandle: Generated<string>;
	updatedAt: Generated<Date>;
}

export interface UserSettings {
	createdAt: Generated<Date>;
	id: Generated<number>;
	targetLocales: Generated<string[]>;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface Verifications {
	createdAt: Date | null;
	expiresAt: Date;
	id: string;
	identifier: string;
	updatedAt: Date | null;
	value: string;
}

export interface WordGlosses {
	aiModel: string | null;
	createdAt: Generated<Date>;
	id: Generated<number>;
	locale: string;
	point: Generated<number>;
	text: string;
	userId: string;
	wordId: number;
}

export interface WordGlossVotes {
	createdAt: Generated<Date>;
	glossId: number;
	isUpvote: boolean;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface DB {
	accounts: Accounts;
	geminiApiKeys: GeminiApiKeys;
	importFiles: ImportFiles;
	importRuns: ImportRuns;
	notifications: Notifications;
	pageLocaleTranslationProofs: PageLocaleTranslationProofs;
	segmentAnnotationLinks: SegmentAnnotationLinks;
	segmentMetadata: SegmentMetadata;
	segmentMetadataTypes: SegmentMetadataTypes;
	segments: Segments;
	segmentTranslations: SegmentTranslations;
	segmentWords: SegmentWords;
	selectedSegmentTranslations: SelectedSegmentTranslations;
	selectedWordGlosses: SelectedWordGlosses;
	sessions: Sessions;
	tipitakaPageAnnotationTargets: TipitakaPageAnnotationTargets;
	tipitakaPages: TipitakaPages;
	tipitakaReadModelJobs: TipitakaReadModelJobs;
	translationJobs: TranslationJobs;
	translationVotes: TranslationVotes;
	users: Users;
	userSettings: UserSettings;
	verifications: Verifications;
	wordGlosses: WordGlosses;
	wordGlossVotes: WordGlossVotes;
}
