/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type {
	JsonValue,
	PageStatus,
	SegmentTypeKey,
	TranslationProofStatus,
	TranslationStatus,
} from "../drizzle/types";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface Accounts {
	accessToken: string | null;
	accessTokenExpiresAt: Date | null;
	accountId: string;
	createdAt: Generated<Date>;
	id: string;
	idToken: string | null;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	refreshTokenExpiresAt: Date | null;
	scope: string | null;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface GeminiApiKeys {
	apiKey: Generated<string>;
	id: Generated<number>;
	userId: string;
}

export interface ImportFiles {
	checksum: string;
	createdAt: Generated<Date>;
	id: Generated<number>;
	importRunId: number;
	message: Generated<string>;
	path: string;
	status: Generated<string>;
}

export interface ImportRuns {
	finishedAt: Date | null;
	id: Generated<number>;
	startedAt: Generated<Date>;
	status: Generated<string>;
}

export interface Notifications {
	actorId: string;
	createdAt: Generated<Date>;
	id: Generated<number>;
	read: Generated<boolean>;
	segmentTranslationId: number;
	userId: string;
}

export interface PageLocaleTranslationProofs {
	id: Generated<number>;
	locale: string;
	pageId: number;
	translationProofStatus: Generated<TranslationProofStatus>;
}

export interface Pages {
	archivedAt: Date | null;
	createdAt: Generated<Date>;
	id: Generated<number>;
	mdastJson: JsonValue;
	order: Generated<number>;
	parentId: number | null;
	publishedAt: Date | null;
	slug: string;
	sourceLocale: Generated<string>;
	status: Generated<PageStatus>;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface PersonalAccessTokens {
	createdAt: Generated<Date>;
	id: Generated<number>;
	keyHash: string;
	lastUsedAt: Date | null;
	name: Generated<string>;
	userId: string;
}

export interface SegmentAnnotationLinks {
	annotationSegmentId: number;
	createdAt: Generated<Date>;
	mainSegmentId: number;
}

export interface SegmentMetadata {
	createdAt: Generated<Date>;
	id: Generated<number>;
	metadataTypeId: number;
	segmentId: number;
	value: string;
}

export interface SegmentMetadataTypes {
	id: Generated<number>;
	key: string;
	label: string;
}

export interface Segments {
	contentId: number;
	createdAt: Generated<Date>;
	id: Generated<number>;
	number: number;
	segmentTypeId: number;
	text: string;
	textAndOccurrenceHash: string;
}

export interface SegmentTranslations {
	createdAt: Generated<Date>;
	id: Generated<number>;
	locale: string;
	point: Generated<number>;
	segmentId: number;
	text: string;
	userId: string;
}

export interface SegmentTypes {
	id: Generated<number>;
	key: SegmentTypeKey;
	label: string;
}

export interface Sessions {
	createdAt: Generated<Date>;
	expiresAt: Date;
	id: string;
	ipAddress: string | null;
	token: string;
	updatedAt: Generated<Date>;
	userAgent: string | null;
	userId: string;
}

export interface TranslationContexts {
	context: string;
	createdAt: Generated<Date>;
	id: Generated<number>;
	name: string;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface TranslationJobs {
	aiModel: string;
	createdAt: Generated<Date>;
	error: Generated<string>;
	id: Generated<number>;
	locale: string;
	pageId: number;
	progress: Generated<number>;
	status: Generated<TranslationStatus>;
	updatedAt: Generated<Date>;
	userId: string | null;
}

export interface TranslationVotes {
	createdAt: Generated<Date>;
	isUpvote: boolean;
	translationId: number;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface Users {
	createdAt: Generated<Date>;
	email: string;
	emailVerified: boolean | null;
	handle: string;
	id: string;
	image: Generated<string>;
	isAi: Generated<boolean>;
	name: Generated<string>;
	plan: Generated<string>;
	profile: Generated<string>;
	provider: Generated<string>;
	totalPoints: Generated<number>;
	twitterHandle: Generated<string>;
	updatedAt: Generated<Date>;
}

export interface UserSettings {
	createdAt: Generated<Date>;
	id: Generated<number>;
	targetLocales: Generated<string[]>;
	updatedAt: Generated<Date>;
	userId: string;
}

export interface Verifications {
	createdAt: Date | null;
	expiresAt: Date;
	id: string;
	identifier: string;
	updatedAt: Date | null;
	value: string;
}

export interface DB {
	accounts: Accounts;
	geminiApiKeys: GeminiApiKeys;
	importFiles: ImportFiles;
	importRuns: ImportRuns;
	notifications: Notifications;
	pageLocaleTranslationProofs: PageLocaleTranslationProofs;
	pages: Pages;
	personalAccessTokens: PersonalAccessTokens;
	segmentAnnotationLinks: SegmentAnnotationLinks;
	segmentMetadata: SegmentMetadata;
	segmentMetadataTypes: SegmentMetadataTypes;
	segments: Segments;
	segmentTranslations: SegmentTranslations;
	segmentTypes: SegmentTypes;
	sessions: Sessions;
	translationContexts: TranslationContexts;
	translationJobs: TranslationJobs;
	translationVotes: TranslationVotes;
	users: Users;
	userSettings: UserSettings;
	verifications: Verifications;
}
