/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleCommonRouteImport } from './routes/$locale._common'
import { Route as LocaleMaintenanceRouteImport } from './routes/$locale.maintenance'
import { Route as LocalePrivacyRouteImport } from './routes/$locale.privacy'
import { Route as LocaleTermsRouteImport } from './routes/$locale.terms'
import { Route as ApiLocaleInfoRouteImport } from './routes/api/locale-info'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiSegmentTranslationsRouteImport } from './routes/api/segment-translations'
import { Route as ApiSentryExampleApiRouteImport } from './routes/api/sentry-example-api'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiTranslationJobsRouteImport } from './routes/api/translation-jobs'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as LocaleCommonIndexRouteImport } from './routes/$locale._common.index'
import { Route as LocaleCommonHandleRouteImport } from './routes/$locale._common.$handle'
import { Route as LocaleCommonSearchRouteImport } from './routes/$locale._common.search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTranslateChunkRouteImport } from './routes/api/translate/chunk'
import { Route as SitemapSitemapChar123idChar125DotxmlRouteImport } from './routes/sitemap/sitemap/{$id}[.]xml'
import { Route as LocaleCommonHandleEditRouteImport } from './routes/$locale._common.$handle.edit'
import { Route as LocaleCommonHandlePageSlugRouteImport } from './routes/$locale._common.$handle_.$pageSlug'
import { Route as LocaleCommonAuthLoginRouteImport } from './routes/$locale._common.auth.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCommonRoute = LocaleCommonRouteImport.update({
  id: '/_common',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMaintenanceRoute = LocaleMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiLocaleInfoRoute = ApiLocaleInfoRouteImport.update({
  id: '/api/locale-info',
  path: '/api/locale-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSegmentTranslationsRoute = ApiSegmentTranslationsRouteImport.update({
  id: '/api/segment-translations',
  path: '/api/segment-translations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryExampleApiRoute = ApiSentryExampleApiRouteImport.update({
  id: '/api/sentry-example-api',
  path: '/api/sentry-example-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationJobsRoute = ApiTranslationJobsRouteImport.update({
  id: '/api/translation-jobs',
  path: '/api/translation-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCommonIndexRoute = LocaleCommonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleCommonRoute,
} as any)
const LocaleCommonHandleRoute = LocaleCommonHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => LocaleCommonRoute,
} as any)
const LocaleCommonSearchRoute = LocaleCommonSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleCommonRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateChunkRoute = ApiTranslateChunkRouteImport.update({
  id: '/chunk',
  path: '/chunk',
  getParentRoute: () => ApiTranslateRoute,
} as any)
const SitemapSitemapChar123idChar125DotxmlRoute =
  SitemapSitemapChar123idChar125DotxmlRouteImport.update({
    id: '/sitemap/sitemap/{$id}.xml',
    path: '/sitemap/sitemap/{$id}.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleCommonHandleEditRoute = LocaleCommonHandleEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LocaleCommonHandleRoute,
} as any)
const LocaleCommonHandlePageSlugRoute =
  LocaleCommonHandlePageSlugRouteImport.update({
    id: '/$handle_/$pageSlug',
    path: '/$handle/$pageSlug',
    getParentRoute: () => LocaleCommonRoute,
  } as any)
const LocaleCommonAuthLoginRoute = LocaleCommonAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => LocaleCommonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/maintenance': typeof LocaleMaintenanceRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/api/locale-info': typeof ApiLocaleInfoRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/og': typeof ApiOgRoute
  '/api/segment-translations': typeof ApiSegmentTranslationsRoute
  '/api/sentry-example-api': typeof ApiSentryExampleApiRoute
  '/api/translate': typeof ApiTranslateRouteWithChildren
  '/api/translation-jobs': typeof ApiTranslationJobsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$locale/$handle': typeof LocaleCommonHandleRouteWithChildren
  '/$locale/search': typeof LocaleCommonSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/translate/chunk': typeof ApiTranslateChunkRoute
  '/sitemap/sitemap/{$id}.xml': typeof SitemapSitemapChar123idChar125DotxmlRoute
  '/$locale/': typeof LocaleCommonIndexRoute
  '/$locale/$handle/edit': typeof LocaleCommonHandleEditRoute
  '/$locale/$handle/$pageSlug': typeof LocaleCommonHandlePageSlugRoute
  '/$locale/auth/login': typeof LocaleCommonAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleCommonIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/maintenance': typeof LocaleMaintenanceRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/api/locale-info': typeof ApiLocaleInfoRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/og': typeof ApiOgRoute
  '/api/segment-translations': typeof ApiSegmentTranslationsRoute
  '/api/sentry-example-api': typeof ApiSentryExampleApiRoute
  '/api/translate': typeof ApiTranslateRouteWithChildren
  '/api/translation-jobs': typeof ApiTranslationJobsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$locale/$handle': typeof LocaleCommonHandleRouteWithChildren
  '/$locale/search': typeof LocaleCommonSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/translate/chunk': typeof ApiTranslateChunkRoute
  '/sitemap/sitemap/{$id}.xml': typeof SitemapSitemapChar123idChar125DotxmlRoute
  '/$locale/$handle/edit': typeof LocaleCommonHandleEditRoute
  '/$locale/$handle/$pageSlug': typeof LocaleCommonHandlePageSlugRoute
  '/$locale/auth/login': typeof LocaleCommonAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/_common': typeof LocaleCommonRouteWithChildren
  '/$locale/maintenance': typeof LocaleMaintenanceRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/api/locale-info': typeof ApiLocaleInfoRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/og': typeof ApiOgRoute
  '/api/segment-translations': typeof ApiSegmentTranslationsRoute
  '/api/sentry-example-api': typeof ApiSentryExampleApiRoute
  '/api/translate': typeof ApiTranslateRouteWithChildren
  '/api/translation-jobs': typeof ApiTranslationJobsRoute
  '/auth/login': typeof AuthLoginRoute
  '/$locale/_common/$handle': typeof LocaleCommonHandleRouteWithChildren
  '/$locale/_common/search': typeof LocaleCommonSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/translate/chunk': typeof ApiTranslateChunkRoute
  '/sitemap/sitemap/{$id}.xml': typeof SitemapSitemapChar123idChar125DotxmlRoute
  '/$locale/_common/': typeof LocaleCommonIndexRoute
  '/$locale/_common/$handle/edit': typeof LocaleCommonHandleEditRoute
  '/$locale/_common/$handle_/$pageSlug': typeof LocaleCommonHandlePageSlugRoute
  '/$locale/_common/auth/login': typeof LocaleCommonAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/maintenance'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/api/locale-info'
    | '/api/notifications'
    | '/api/og'
    | '/api/segment-translations'
    | '/api/sentry-example-api'
    | '/api/translate'
    | '/api/translation-jobs'
    | '/auth/login'
    | '/$locale/$handle'
    | '/$locale/search'
    | '/api/auth/$'
    | '/api/translate/chunk'
    | '/sitemap/sitemap/{$id}.xml'
    | '/$locale/'
    | '/$locale/$handle/edit'
    | '/$locale/$handle/$pageSlug'
    | '/$locale/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/maintenance'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/api/locale-info'
    | '/api/notifications'
    | '/api/og'
    | '/api/segment-translations'
    | '/api/sentry-example-api'
    | '/api/translate'
    | '/api/translation-jobs'
    | '/auth/login'
    | '/$locale/$handle'
    | '/$locale/search'
    | '/api/auth/$'
    | '/api/translate/chunk'
    | '/sitemap/sitemap/{$id}.xml'
    | '/$locale/$handle/edit'
    | '/$locale/$handle/$pageSlug'
    | '/$locale/auth/login'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/_common'
    | '/$locale/maintenance'
    | '/$locale/privacy'
    | '/$locale/terms'
    | '/api/locale-info'
    | '/api/notifications'
    | '/api/og'
    | '/api/segment-translations'
    | '/api/sentry-example-api'
    | '/api/translate'
    | '/api/translation-jobs'
    | '/auth/login'
    | '/$locale/_common/$handle'
    | '/$locale/_common/search'
    | '/api/auth/$'
    | '/api/translate/chunk'
    | '/sitemap/sitemap/{$id}.xml'
    | '/$locale/_common/'
    | '/$locale/_common/$handle/edit'
    | '/$locale/_common/$handle_/$pageSlug'
    | '/$locale/_common/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLocaleInfoRoute: typeof ApiLocaleInfoRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiSegmentTranslationsRoute: typeof ApiSegmentTranslationsRoute
  ApiSentryExampleApiRoute: typeof ApiSentryExampleApiRoute
  ApiTranslateRoute: typeof ApiTranslateRouteWithChildren
  ApiTranslationJobsRoute: typeof ApiTranslationJobsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SitemapSitemapChar123idChar125DotxmlRoute: typeof SitemapSitemapChar123idChar125DotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_common': {
      id: '/$locale/_common'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleCommonRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/maintenance': {
      id: '/$locale/maintenance'
      path: '/maintenance'
      fullPath: '/$locale/maintenance'
      preLoaderRoute: typeof LocaleMaintenanceRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/locale-info': {
      id: '/api/locale-info'
      path: '/api/locale-info'
      fullPath: '/api/locale-info'
      preLoaderRoute: typeof ApiLocaleInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/segment-translations': {
      id: '/api/segment-translations'
      path: '/api/segment-translations'
      fullPath: '/api/segment-translations'
      preLoaderRoute: typeof ApiSegmentTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-example-api': {
      id: '/api/sentry-example-api'
      path: '/api/sentry-example-api'
      fullPath: '/api/sentry-example-api'
      preLoaderRoute: typeof ApiSentryExampleApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translation-jobs': {
      id: '/api/translation-jobs'
      path: '/api/translation-jobs'
      fullPath: '/api/translation-jobs'
      preLoaderRoute: typeof ApiTranslationJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_common/': {
      id: '/$locale/_common/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleCommonIndexRouteImport
      parentRoute: typeof LocaleCommonRoute
    }
    '/$locale/_common/$handle': {
      id: '/$locale/_common/$handle'
      path: '/$handle'
      fullPath: '/$locale/$handle'
      preLoaderRoute: typeof LocaleCommonHandleRouteImport
      parentRoute: typeof LocaleCommonRoute
    }
    '/$locale/_common/search': {
      id: '/$locale/_common/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleCommonSearchRouteImport
      parentRoute: typeof LocaleCommonRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate/chunk': {
      id: '/api/translate/chunk'
      path: '/chunk'
      fullPath: '/api/translate/chunk'
      preLoaderRoute: typeof ApiTranslateChunkRouteImport
      parentRoute: typeof ApiTranslateRoute
    }
    '/sitemap/sitemap/{$id}.xml': {
      id: '/sitemap/sitemap/{$id}.xml'
      path: '/sitemap/sitemap/{$id}.xml'
      fullPath: '/sitemap/sitemap/{$id}.xml'
      preLoaderRoute: typeof SitemapSitemapChar123idChar125DotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_common/$handle/edit': {
      id: '/$locale/_common/$handle/edit'
      path: '/edit'
      fullPath: '/$locale/$handle/edit'
      preLoaderRoute: typeof LocaleCommonHandleEditRouteImport
      parentRoute: typeof LocaleCommonHandleRoute
    }
    '/$locale/_common/$handle_/$pageSlug': {
      id: '/$locale/_common/$handle_/$pageSlug'
      path: '/$handle/$pageSlug'
      fullPath: '/$locale/$handle/$pageSlug'
      preLoaderRoute: typeof LocaleCommonHandlePageSlugRouteImport
      parentRoute: typeof LocaleCommonRoute
    }
    '/$locale/_common/auth/login': {
      id: '/$locale/_common/auth/login'
      path: '/auth/login'
      fullPath: '/$locale/auth/login'
      preLoaderRoute: typeof LocaleCommonAuthLoginRouteImport
      parentRoute: typeof LocaleCommonRoute
    }
  }
}

interface LocaleCommonHandleRouteChildren {
  LocaleCommonHandleEditRoute: typeof LocaleCommonHandleEditRoute
}

const LocaleCommonHandleRouteChildren: LocaleCommonHandleRouteChildren = {
  LocaleCommonHandleEditRoute: LocaleCommonHandleEditRoute,
}

const LocaleCommonHandleRouteWithChildren =
  LocaleCommonHandleRoute._addFileChildren(LocaleCommonHandleRouteChildren)

interface LocaleCommonRouteChildren {
  LocaleCommonHandleRoute: typeof LocaleCommonHandleRouteWithChildren
  LocaleCommonSearchRoute: typeof LocaleCommonSearchRoute
  LocaleCommonIndexRoute: typeof LocaleCommonIndexRoute
  LocaleCommonHandlePageSlugRoute: typeof LocaleCommonHandlePageSlugRoute
  LocaleCommonAuthLoginRoute: typeof LocaleCommonAuthLoginRoute
}

const LocaleCommonRouteChildren: LocaleCommonRouteChildren = {
  LocaleCommonHandleRoute: LocaleCommonHandleRouteWithChildren,
  LocaleCommonSearchRoute: LocaleCommonSearchRoute,
  LocaleCommonIndexRoute: LocaleCommonIndexRoute,
  LocaleCommonHandlePageSlugRoute: LocaleCommonHandlePageSlugRoute,
  LocaleCommonAuthLoginRoute: LocaleCommonAuthLoginRoute,
}

const LocaleCommonRouteWithChildren = LocaleCommonRoute._addFileChildren(
  LocaleCommonRouteChildren,
)

interface LocaleRouteChildren {
  LocaleCommonRoute: typeof LocaleCommonRouteWithChildren
  LocaleMaintenanceRoute: typeof LocaleMaintenanceRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleCommonRoute: LocaleCommonRouteWithChildren,
  LocaleMaintenanceRoute: LocaleMaintenanceRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleTermsRoute: LocaleTermsRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface ApiTranslateRouteChildren {
  ApiTranslateChunkRoute: typeof ApiTranslateChunkRoute
}

const ApiTranslateRouteChildren: ApiTranslateRouteChildren = {
  ApiTranslateChunkRoute: ApiTranslateChunkRoute,
}

const ApiTranslateRouteWithChildren = ApiTranslateRoute._addFileChildren(
  ApiTranslateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLocaleInfoRoute: ApiLocaleInfoRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOgRoute: ApiOgRoute,
  ApiSegmentTranslationsRoute: ApiSegmentTranslationsRoute,
  ApiSentryExampleApiRoute: ApiSentryExampleApiRoute,
  ApiTranslateRoute: ApiTranslateRouteWithChildren,
  ApiTranslationJobsRoute: ApiTranslationJobsRoute,
  AuthLoginRoute: AuthLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SitemapSitemapChar123idChar125DotxmlRoute:
    SitemapSitemapChar123idChar125DotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
